GET http://localhost:2410/test

################################

POST http://localhost:2410/register
Content-Type: application/json

{
  "vorname": "Lukas",
  "nachname": "Semler",
  "email": "lukas.semler@gmail.com", 
  "password": "Lukas1", 
  "type": "Trainer", 
  "avatarPath": "blablabla"
}

#################
POST http://localhost:2410/addTeam
Content-Type: application/json

{
  "titel": "test",
  "beschreibung": "bla",
  "farbe": "#11111", 
  "zugangscode": "sefased", 
  "t_id": 1
}

#######


GET http://localhost:2410/getAllSpieler

#######


PATCH http://localhost:2410/changeSpielerData
Content-Type: application/json

{
  "spieler_id": 22,
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@gmail.com",
  "passwort": "123456",
  "avatare": "/Avatare/Avatar9.png"
}


############# Alle Spieler von einer Mannschaft bekommen
GET http://localhost:2410/getSpieler/15