GET http://localhost:2410/test

################################

POST http://localhost:2410/register
Content-Type: application/json

{
  "vorname": "Lukas",
  "nachname": "Semler",
  "email": "lukas.semler@gmail.com", 
  "password": "Lukas1", 
  "type": "Trainer", 
  "avatarPath": "blablabla"
}

#################
POST http://localhost:2410/addTeam
Content-Type: application/json

{
  "titel": "test",
  "beschreibung": "bla",
  "farbe": "#11111", 
  "zugangscode": "sefased", 
  "t_id": 1
}

#######


GET http://localhost:2410/getAllSpieler